#include "../../header/n105_color___/n105_500_utilColor.hpp"
#include "../../header/n119_score___/n119_200_pieceScore.hpp"

const Score g_PieceScore[N31_PieceNone] = {
	ScoreZero,
	PieceScore::m_PawnScore,
	PieceScore::m_LanceScore,
	PieceScore::m_KnightScore,
	PieceScore::m_SilverScore,
	PieceScore::m_BishopScore,
	PieceScore::m_RookScore,
	PieceScore::m_GoldScore,
	ScoreZero, // King
	PieceScore::m_ProPawnScore,
	PieceScore::m_ProLanceScore,
	PieceScore::m_ProKnightScore,
	PieceScore::m_ProSilverScore,
	PieceScore::m_HorseScore,
	PieceScore::m_DragonScore,
	ScoreZero,
	ScoreZero,
	PieceScore::m_PawnScore,
	PieceScore::m_LanceScore,
	PieceScore::m_KnightScore,
	PieceScore::m_SilverScore,
	PieceScore::m_BishopScore,
	PieceScore::m_RookScore,
	PieceScore::m_GoldScore,
	ScoreZero, // King
	PieceScore::m_ProPawnScore,
	PieceScore::m_ProLanceScore,
	PieceScore::m_ProKnightScore,
	PieceScore::m_ProSilverScore,
	PieceScore::m_HorseScore,
	PieceScore::m_DragonScore,
};
const Score g_CapturePieceScore[N31_PieceNone] = {
	ScoreZero,
	PieceScore::m_CapturePawnScore,
	PieceScore::m_CaptureLanceScore,
	PieceScore::m_CaptureKnightScore,
	PieceScore::m_CaptureSilverScore,
	PieceScore::m_CaptureBishopScore,
	PieceScore::m_CaptureRookScore,
	PieceScore::m_CaptureGoldScore,
	ScoreZero, // King
	PieceScore::m_CaptureProPawnScore,
	PieceScore::m_CaptureProLanceScore,
	PieceScore::m_CaptureProKnightScore,
	PieceScore::m_CaptureProSilverScore,
	PieceScore::m_CaptureHorseScore,
	PieceScore::m_CaptureDragonScore,
	ScoreZero,
	ScoreZero,
	PieceScore::m_CapturePawnScore,
	PieceScore::m_CaptureLanceScore,
	PieceScore::m_CaptureKnightScore,
	PieceScore::m_CaptureSilverScore,
	PieceScore::m_CaptureBishopScore,
	PieceScore::m_CaptureRookScore,
	PieceScore::m_CaptureGoldScore,
	ScoreZero, // King
	PieceScore::m_CaptureProPawnScore,
	PieceScore::m_CaptureProLanceScore,
	PieceScore::m_CaptureProKnightScore,
	PieceScore::m_CaptureProSilverScore,
	PieceScore::m_CaptureHorseScore,
	PieceScore::m_CaptureDragonScore,
};
const Score g_PromotePieceScore[7] = {
	ScoreZero,
	PieceScore::m_PromotePawnScore,
	PieceScore::m_PromoteLanceScore,
	PieceScore::m_PromoteKnightScore,
	PieceScore::m_PromoteSilverScore,
	PieceScore::m_PromoteBishopScore,
	PieceScore::m_PromoteRookScore
};
